In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from math import floor
from random import sample
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

sns.set(color_codes=True)

Calling the functions file

In [4]:
%run ./CVGI_MR_00_functions.ipynb

Populating the interactive namespace from numpy and matplotlib

initiating

In [5]:
imports()

What is the source of the MOVEMENT data? (1=internet, 2=home Mac, 3=office Windows) 2
What type of import is it? (1 = initial (only cases and movement), 2 = initial (full), 3 = data by week, 4 = merged datasets, 5 = only cases) 1

../../../02 data
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6533090 entries, 0 to 6533089
Data columns (total 9 columns):
 #   Column                                      Dtype
---  ------                                      -----
 0   ds                                          datetime64[ns]
 1   country                                     object
 2   polygon_source                              object
 3   polygon_id                                  object
 4   polygon_name                                object
 5   all_day_bing_tiles_visited_relative_change  float64
 6   all_day_ratio_single_tile_users             float64
 7   baseline_name                               object
 8   baseline_type                               object
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 448.6+ MB

========================================================================
+++++++++++++++++++++++++++++Movement Range+++++++++++++++++++++++++++++
========================================================================
 None
../../../02 data/BR BRASIL.IO/2021-05-25 caso_full.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2135152 entries, 0 to 2135151
Data columns (total 18 columns):
 #   Column                                         Dtype
---  ------                                         -----
 0   city                                           object
 1   city_ibge_code                                 float64
 2   date                                           datetime64[ns]
 3   epidemiological_week                           int64
 4   estimated_population                           float64
 5   estimated_population_2019                      float64
 6   is_last                                        bool
 7   is_repeated                                    bool
 8   last_available_confirmed                       int64
 9   last_available_confirmed_per_100k_inhabitants  float64
 10  last_available_date                            object
 11  last_available_death_rate                      float64
 12  last_available_deaths                          int64
 13  order_for_place                                int64
 14  place_type                                     object
 15  state                                          object
 16  new_confirmed                                  int64
 17  new_deaths                                     int64
dtypes: bool(2), datetime64[ns](1), float64(5), int64(6), object(4)
memory usage: 264.7+ MB

=========================================================================
+++++++++++++++++++++++++Daily Cases (Brasil.io)+++++++++++++++++++++++++
=========================================================================
 None

---

<h4> Preparation of initial data </h4>
Prepares datasets to group data by epidemiological week.

In [6]:
drops()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1191144 entries, 416072 to 1607215
Data columns (total 6 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   date             1191144 non-null  datetime64[ns]
 1   country          1191144 non-null  object
 2   GADM_GID_2       1191144 non-null  object
 3   mun_name         1191144 non-null  object
 4   movement_change  1191144 non-null  float64
 5   stay_put         1191144 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 63.6+ MB

=========================================================================
+++++++++++++++++++++++++Movement Range, dropped+++++++++++++++++++++++++
=========================================================================
 None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 2123295 entries, 0 to 2135150
Data columns (total 11 columns):
 #   Column                Dtype
---  ------                -----
 0   mun_name              object
 1   ibge_code             object
 2   date                  datetime64[ns]
 3   epidemiological_week  int64
 4   pop_2019              float64
 5   is_last               bool
 6   is_repeated           bool
 7   acc_cases             int64
 8   acc_deaths            int64
 9   new_cases             int64
 10  new_deaths            int64
dtypes: bool(2), datetime64[ns](1), float64(1), int64(5), object(2)
memory usage: 166.0+ MB

========================================================================
+++++++++++++++++++++++++++++Cases, dropped+++++++++++++++++++++++++++++
========================================================================
 None

---

In [7]:
cases

,mun_name,ibge_code,date,epidemiological_week,pop_2019,is_last,is_repeated,acc_cases,acc_deaths,new_cases,new_deaths
0,Rio Branco,1200401,2020-03-17,202012,407319.0,False,False,3,0,3,0
2,Rio Branco,1200401,2020-03-18,202012,407319.0,False,False,3,0,0,0
4,Rio Branco,1200401,2020-03-19,202012,407319.0,False,False,4,0,1,0
6,Rio Branco,1200401,2020-03-20,202012,407319.0,False,False,7,0,3,0
8,Rio Branco,1200401,2020-03-21,202012,407319.0,False,False,11,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...
2135146,Tocantínia,1721109,2021-05-25,202121,7545.0,False,True,680,10,0,0
2135147,Tupirama,1721257,2021-05-25,202121,1891.0,False,True,143,2,0,0
2135148,Tupiratins,1721307,2021-05-25,202121,2671.0,False,True,80,1,0,0
2135149,Wanderlândia,1722081,2021-05-25,202121,11683.0,False,True,773,11,0,0
2135150,Xambioá,1722107,2021-05-25,202121,11540.0,False,True,2031,27,0,0

In [116]:
cases.drop('epi_week', axis=1, inplace=True)

In [117]:
randSample = sorted(sample(range(2123295),k=55))
%run ./CVGI_MR_00_functions.ipynb

In [100]:
rows = randSample
cases = new_columns(cases,['epi_week'])
    #print(rows)    
for i in range(len(cases.iloc[1:100])):
    week_txt = right(str(cases.epidemiological_week.iloc[i]),2) #Brasil.io always codes "epidemiological_week" with 6 digits
    year_txt = left(str(cases.epidemiological_week.iloc[i]),4)
    cases.epi_week.iloc[i] = year_txt + "." + week_txt
cases.iloc[1:100]

,mun_name,ibge_code,date,epidemiological_week,pop_2019,is_last,is_repeated,acc_cases,acc_deaths,new_confirmed,new_deaths,epi_week
2,Rio Branco,1200401,2020-03-18,202012,407319.0,False,False,3,0,0,0,2020.12
4,Rio Branco,1200401,2020-03-19,202012,407319.0,False,False,4,0,1,0,2020.12
6,Rio Branco,1200401,2020-03-20,202012,407319.0,False,False,7,0,3,0,2020.12
8,Rio Branco,1200401,2020-03-21,202012,407319.0,False,False,11,0,4,0,2020.12
10,Rio Branco,1200401,2020-03-22,202013,407319.0,False,False,11,0,0,0,2020.13
...,...,...,...,...,...,...,...,...,...,...,...,...
126,Cruzeiro do Sul,1200203,2020-04-17,202016,88376.0,False,False,2,0,0,0,2020.16
127,Plácido de Castro,1200385,2020-04-17,202016,19761.0,False,False,14,1,1,0,2020.16
128,Porto Acre,1200807,2020-04-17,202016,18504.0,False,False,1,0,0,0,2020.16
129,Rio Branco,1200401,2020-04-17,202016,407319.0,False,False,105,4,19,0,2020.16
131,Acrelândia,1200013,2020-04-18,202016,15256.0,False,False,12,0,0,0,n

In [ ]:
cases_week = cases_cleanup(None,True,False)

In [114]:
cases_week.head()

,,new_confirmed,new_deaths,acc_cases,acc_deaths,pop_2019,epi_week_col,acc_cases_100k,acc_deaths_1mi
ibge_code,epi_week,,,,,,,,
1100015,n,3640,61,510470,7012,22945.0,n,2224754.85,305600.35
1100023,n,19608,427,2954606,55358,107863.0,n,2739221.05,513225.11
1100031,n,680,18,89291,2438,5312.0,n,1680929.97,458960.84
1100049,n,11991,236,1629546,25312,85359.0,n,1909050.01,296535.81
1100056,n,2199,55,231936,5005,16323.0,n,1420915.27,306622.56

In [8]:
cases.date.min()

Timestamp('2020-02-25 00:00:00')

In [9]:
cases.date.max()

Timestamp('2021-05-25 00:00:00')

In [12]:
cases[cases.date == "2021-01-01"]

,mun_name,ibge_code,date,epidemiological_week,pop_2019,is_last,is_repeated,acc_cases,acc_deaths,new_cases,new_deaths
5777,Acrelândia,1200013,2021-01-01,202053,15256.0,False,False,563,12,0,0
5778,Assis Brasil,1200054,2021-01-01,202053,7417.0,False,False,762,9,0,0
5779,Brasiléia,1200104,2021-01-01,202053,26278.0,False,False,1298,22,0,0
5780,Bujari,1200138,2021-01-01,202053,10266.0,False,False,491,8,0,0
5781,Capixaba,1200179,2021-01-01,202053,11733.0,False,False,305,8,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2114986,Tocantínia,1721109,2021-01-01,202053,7545.0,False,False,423,5,1,0
2114987,Tupirama,1721257,2021-01-01,202053,1891.0,False,False,115,2,0,0
2114988,Tupiratins,1721307,2021-01-01,202053,2671.0,False,False,33,0,0,0
2114989,Wanderlândia,1722081,2021-01-01,202053,11683.0,False,False,460,6,0,0
2114990,Xambioá,1722107,2021-01-01,202053,11540.0,False,False,1064,15,0,0